INSERT INTO localities (name, id_province, prefix) values ("12 de octubre", 1, "2317");
INSERT INTO localities (name, id_province, prefix) values ("17 de agosto", 1, "2924");
INSERT INTO localities (name, id_province, prefix) values ("25 de mayo (prov. Buenos aires)", 1, "2345");
INSERT INTO localities (name, id_province, prefix) values ("30 de agosto", 1, "2392");
INSERT INTO localities (name, id_province, prefix) values ("Abasto", 1, "221");
INSERT INTO localities (name, id_province, prefix) values ("Abbott", 1, "2271");
INSERT INTO localities (name, id_province, prefix) values ("Acevedo", 1, "2477");
INSERT INTO localities (name, id_province, prefix) values ("Adolfo gonzalez chaves", 1, "2983");
INSERT INTO localities (name, id_province, prefix) values ("Agustin roca", 1, "236");
INSERT INTO localities (name, id_province, prefix) values ("Alberti", 1, "2346");
INSERT INTO localities (name, id_province, prefix) values ("Alejandro korn", 1, "2225");
INSERT INTO localities (name, id_province, prefix) values ("Alejandro petion", 1, "2226");
INSERT INTO localities (name, id_province, prefix) values ("Algarrobo", 1, "2927");
INSERT INTO localities (name, id_province, prefix) values ("Alsina", 1, "3329");
INSERT INTO localities (name, id_province, prefix) values ("Altamirano (prov. Buenos aires)", 1, "2223");
INSERT INTO localities (name, id_province, prefix) values ("Alvarez de toledo", 1, "2344");
INSERT INTO localities (name, id_province, prefix) values ("Amba (capital federal y gran buenos aires)", 1, "11");
INSERT INTO localities (name, id_province, prefix) values ("Ameghino", 1, "3388");
INSERT INTO localities (name, id_province, prefix) values ("America", 1, "2337");
INSERT INTO localities (name, id_province, prefix) values ("Antonio carboni", 1, "2227");
INSERT INTO localities (name, id_province, prefix) values ("Arboledas", 1, "2316");
INSERT INTO localities (name, id_province, prefix) values ("Arenaza", 1, "2355");
INSERT INTO localities (name, id_province, prefix) values ("Arrecifes", 1, "2478");
INSERT INTO localities (name, id_province, prefix) values ("Arribenos", 1, "2353");
INSERT INTO localities (name, id_province, prefix) values ("Arroyo corto", 1, "2923");
INSERT INTO localities (name, id_province, prefix) values ("Atalaya", 1, "2221");
INSERT INTO localities (name, id_province, prefix) values ("Ayacucho", 1, "2296");
INSERT INTO localities (name, id_province, prefix) values ("Azcuenaga", 1, "2325");
INSERT INTO localities (name, id_province, prefix) values ("Azul", 1, "2281");
INSERT INTO localities (name, id_province, prefix) values ("Bahia blanca", 1, "291");
INSERT INTO localities (name, id_province, prefix) values ("Bajo hondo", 1, "2932");
INSERT INTO localities (name, id_province, prefix) values ("Balcarce", 1, "2266");
INSERT INTO localities (name, id_province, prefix) values ("Balneario pehuen co", 1, "2921");
INSERT INTO localities (name, id_province, prefix) values ("Barrio el casal", 1, "223");
INSERT INTO localities (name, id_province, prefix) values ("Barrio mi rincon", 1, "237");
INSERT INTO localities (name, id_province, prefix) values ("Bellocq", 1, "2395");
INSERT INTO localities (name, id_province, prefix) values ("Benavidez", 1, "3327");
INSERT INTO localities (name, id_province, prefix) values ("Benito juarez", 1, "2292");
INSERT INTO localities (name, id_province, prefix) values ("Bernasconi", 1, "2925");
INSERT INTO localities (name, id_province, prefix) values ("Bolivar", 1, "2314");
INSERT INTO localities (name, id_province, prefix) values ("Bonifacio", 1, "2929");
INSERT INTO localities (name, id_province, prefix) values ("Bragado", 1, "2342");
INSERT INTO localities (name, id_province, prefix) values ("Brahma", 1, "2323");
INSERT INTO localities (name, id_province, prefix) values ("Campana", 1, "3489");
INSERT INTO localities (name, id_province, prefix) values ("Campos salles", 1, "336");
INSERT INTO localities (name, id_province, prefix) values ("Canada seca (prov. Buenos aires)", 1, "3382");
INSERT INTO localities (name, id_province, prefix) values ("Carabelas", 1, "2475");
INSERT INTO localities (name, id_province, prefix) values ("Carhue", 1, "2936");
INSERT INTO localities (name, id_province, prefix) values ("Carilo", 1, "2254");
INSERT INTO localities (name, id_province, prefix) values ("Carlos salas", 1, "2357");
INSERT INTO localities (name, id_province, prefix) values ("Carlos spegazzini", 1, "2274");
INSERT INTO localities (name, id_province, prefix) values ("Carmen de areco", 1, "2273");
INSERT INTO localities (name, id_province, prefix) values ("Castelli", 1, "2245");
INSERT INTO localities (name, id_province, prefix) values ("Castilla", 1, "2324");
INSERT INTO localities (name, id_province, prefix) values ("Chacabuco", 1, "2352");
INSERT INTO localities (name, id_province, prefix) values ("Chascomus", 1, "2241");
INSERT INTO localities (name, id_province, prefix) values ("Chiclana", 1, "2396");
INSERT INTO localities (name, id_province, prefix) values ("Claraz", 1, "2264");
INSERT INTO localities (name, id_province, prefix) values ("Claromeco", 1, "2982");
INSERT INTO localities (name, id_province, prefix) values ("Colon (prov. Buenos aires)", 1, "2473");
INSERT INTO localities (name, id_province, prefix) values ("Comandante n. Otamendi", 1, "2291");
INSERT INTO localities (name, id_province, prefix) values ("Coronel granada", 1, "2356");
INSERT INTO localities (name, id_province, prefix) values ("Coronel pringles", 1, "2922");
INSERT INTO localities (name, id_province, prefix) values ("Coronel suarez", 1, "2926");
INSERT INTO localities (name, id_province, prefix) values ("Coronel vidal", 1, "2265");
INSERT INTO localities (name, id_province, prefix) values ("Del viso", 1, "2320");
INSERT INTO localities (name, id_province, prefix) values ("Derqui", 1, "230");
INSERT INTO localities (name, id_province, prefix) values ("Dique lujan", 1, "348");
INSERT INTO localities (name, id_province, prefix) values ("Duggan", 1, "2326");
INSERT INTO localities (name, id_province, prefix) values ("El dorado", 1, "2354");
INSERT INTO localities (name, id_province, prefix) values ("El paraiso", 1, "3407");
INSERT INTO localities (name, id_province, prefix) values ("El pato", 1, "2229");
INSERT INTO localities (name, id_province, prefix) values ("Elvira", 1, "2343");
INSERT INTO localities (name, id_province, prefix) values ("Gahan", 1, "2474");
INSERT INTO localities (name, id_province, prefix) values ("Gardey", 1, "249");
INSERT INTO localities (name, id_province, prefix) values ("General belgrano", 1, "2243");
INSERT INTO localities (name, id_province, prefix) values ("General guido", 1, "2268");
INSERT INTO localities (name, id_province, prefix) values ("General lamadrid", 1, "2286");
INSERT INTO localities (name, id_province, prefix) values ("General las heras", 1, "220");
INSERT INTO localities (name, id_province, prefix) values ("General lavalle (prov. Buenos aires)", 1, "2252");
INSERT INTO localities (name, id_province, prefix) values ("General madariaga", 1, "2267");
INSERT INTO localities (name, id_province, prefix) values ("Glew", 1, "2224");
INSERT INTO localities (name, id_province, prefix) values ("Gonzalez catan", 1, "2202");
INSERT INTO localities (name, id_province, prefix) values ("Hilario ascasubi", 1, "2928");
INSERT INTO localities (name, id_province, prefix) values ("Hinojo", 1, "2284");
INSERT INTO localities (name, id_province, prefix) values ("Huanguelen sur", 1, "2933");
INSERT INTO localities (name, id_province, prefix) values ("Ingeniero thomson", 1, "2394");
INSERT INTO localities (name, id_province, prefix) values ("Laprida", 1, "2285");
INSERT INTO localities (name, id_province, prefix) values ("Las flores (prov. Buenos aires)", 1, "2244");
INSERT INTO localities (name, id_province, prefix) values ("Las marianas", 1, "2272");
INSERT INTO localities (name, id_province, prefix) values ("Lezama", 1, "2242");
INSERT INTO localities (name, id_province, prefix) values ("Lima", 1, "3487");
INSERT INTO localities (name, id_province, prefix) values ("Loberia", 1, "2261");
INSERT INTO localities (name, id_province, prefix) values ("Los toldos (prov. Buenos aires)", 1, "2358");
INSERT INTO localities (name, id_province, prefix) values ("Mar de ajo", 1, "2257");
INSERT INTO localities (name, id_province, prefix) values ("Necochea", 1, "2262");
INSERT INTO localities (name, id_province, prefix) values ("Rauch", 1, "2297");
INSERT INTO localities (name, id_province, prefix) values ("Rivera", 1, "2935");
INSERT INTO localities (name, id_province, prefix) values ("Salazar", 1, "2393");
INSERT INTO localities (name, id_province, prefix) values ("Santa teresita", 1, "2246");
INSERT INTO localities (name, id_province, prefix) values ("Tapalque", 1, "2283");
INSERT INTO localities (name, id_province, prefix) values ("Villa gesell", 1, "2255");
INSERT INTO localities (name, id_province, prefix) values ("Alijilan", 2, "383");
INSERT INTO localities (name, id_province, prefix) values ("Amanao", 2, "3835");
INSERT INTO localities (name, id_province, prefix) values ("Ancasti", 2, "3832");
INSERT INTO localities (name, id_province, prefix) values ("Copacabana (prov. Catamarca)", 2, "3837");
INSERT INTO localities (name, id_province, prefix) values ("El cajon", 2, "3838");
INSERT INTO localities (name, id_province, prefix) values ("Avia terai", 3, "364");
INSERT INTO localities (name, id_province, prefix) values ("Barranqueras", 3, "362");
INSERT INTO localities (name, id_province, prefix) values ("Capitan solari", 3, "3725");
INSERT INTO localities (name, id_province, prefix) values ("Charadai", 3, "3721");
INSERT INTO localities (name, id_province, prefix) values ("Charata", 3, "3731");
INSERT INTO localities (name, id_province, prefix) values ("Colonia d. Matheu", 3, "3735");
INSERT INTO localities (name, id_province, prefix) values ("Colonia elisa", 3, "3734");
INSERT INTO localities (name, id_province, prefix) values ("Comandante frias", 3, "3711");
INSERT INTO localities (name, id_province, prefix) values ("Nueva pompeya", 3, "3715");
INSERT INTO localities (name, id_province, prefix) values ("Taco pozo", 3, "3877");
INSERT INTO localities (name, id_province, prefix) values ("28 de julio", 4, "280");
INSERT INTO localities (name, id_province, prefix) values ("Aldea beleiro", 4, "2903");
INSERT INTO localities (name, id_province, prefix) values ("Aldea epulef", 4, "2945");
INSERT INTO localities (name, id_province, prefix) values ("Astra", 4, "297");
INSERT INTO localities (name, id_province, prefix) values ("Las golondrinas", 4, "294");
INSERT INTO localities (name, id_province, prefix) values ("Achiras", 5, "3582");
INSERT INTO localities (name, id_province, prefix) values ("Adelia maria", 5, "3585");
INSERT INTO localities (name, id_province, prefix) values ("Agua de las piedras", 5, "3525");
INSERT INTO localities (name, id_province, prefix) values ("Agua de oro (dto. Rio seco)", 5, "3522");
INSERT INTO localities (name, id_province, prefix) values ("Agua del crispin", 5, "3542");
INSERT INTO localities (name, id_province, prefix) values ("Agua hedionda", 5, "3521");
INSERT INTO localities (name, id_province, prefix) values ("Aguas de ramon", 5, "3549");
INSERT INTO localities (name, id_province, prefix) values ("Alcira", 5, "358");
INSERT INTO localities (name, id_province, prefix) values ("Alejo ledesma", 5, "3468");
INSERT INTO localities (name, id_province, prefix) values ("Alicia", 5, "3533");
INSERT INTO localities (name, id_province, prefix) values ("Almafuerte (prov. Cordoba)", 5, "3571");
INSERT INTO localities (name, id_province, prefix) values ("Alta gracia", 5, "3547");
INSERT INTO localities (name, id_province, prefix) values ("Alto alegre", 5, "3537");
INSERT INTO localities (name, id_province, prefix) values ("Altos de chipion", 5, "3562");
INSERT INTO localities (name, id_province, prefix) values ("Amboy", 5, "3546");
INSERT INTO localities (name, id_province, prefix) values ("Arguello", 5, "3543");
INSERT INTO localities (name, id_province, prefix) values ("Arroyito (prov. Cordoba)", 5, "3576");
INSERT INTO localities (name, id_province, prefix) values ("Arroyo algodon", 5, "353");
INSERT INTO localities (name, id_province, prefix) values ("Arteaga", 5, "3467");
INSERT INTO localities (name, id_province, prefix) values ("Atahona", 5, "3575");
INSERT INTO localities (name, id_province, prefix) values ("Balnearia", 5, "3563");
INSERT INTO localities (name, id_province, prefix) values ("Benjamin gould", 5, "3463");
INSERT INTO localities (name, id_province, prefix) values ("Bialet masse", 5, "3541");
INSERT INTO localities (name, id_province, prefix) values ("Bouchard", 5, "3387");
INSERT INTO localities (name, id_province, prefix) values ("Bouwer", 5, "351");
INSERT INTO localities (name, id_province, prefix) values ("Calchin", 5, "3573");
INSERT INTO localities (name, id_province, prefix) values ("Calchin oeste", 5, "3532");
INSERT INTO localities (name, id_province, prefix) values ("Canteras iguazu", 5, "3548");
INSERT INTO localities (name, id_province, prefix) values ("Canada del machado norte", 5, "3574");
INSERT INTO localities (name, id_province, prefix) values ("Cienaga de allende", 5, "3544");
INSERT INTO localities (name, id_province, prefix) values ("Colonia castelar", 5, "3564");
INSERT INTO localities (name, id_province, prefix) values ("Colonia flora", 5, "3472");
INSERT INTO localities (name, id_province, prefix) values ("Cosme sur", 5, "3572");
INSERT INTO localities (name, id_province, prefix) values ("Del campillo", 5, "3583");
INSERT INTO localities (name, id_province, prefix) values ("El banado norte", 5, "3524");
INSERT INTO localities (name, id_province, prefix) values ("El rastreador", 5, "3584");
INSERT INTO localities (name, id_province, prefix) values ("General levalle", 5, "3385");
INSERT INTO localities (name, id_province, prefix) values ("Huinca renanco", 5, "2336");
INSERT INTO localities (name, id_province, prefix) values ("9 de julio (prov. Corrientes)", 6, "3777");
INSERT INTO localities (name, id_province, prefix) values ("Aguay", 6, "3773");
INSERT INTO localities (name, id_province, prefix) values ("Alvear", 6, "3772");
INSERT INTO localities (name, id_province, prefix) values ("Angua", 6, "3782");
INSERT INTO localities (name, id_province, prefix) values ("Apipe grande", 6, "3786");
INSERT INTO localities (name, id_province, prefix) values ("Baibiene", 6, "3774");
INSERT INTO localities (name, id_province, prefix) values ("Beron de astrada", 6, "3781");
INSERT INTO localities (name, id_province, prefix) values ("Bompland", 6, "3775");
INSERT INTO localities (name, id_province, prefix) values ("Corrientes", 6, "379");
INSERT INTO localities (name, id_province, prefix) values ("Galarza", 6, "3756");
INSERT INTO localities (name, id_province, prefix) values ("1 de mayo", 7, "3447");
INSERT INTO localities (name, id_province, prefix) values ("20 de setiembre", 7, "3435");
INSERT INTO localities (name, id_province, prefix) values ("Alcaraz", 7, "3438");
INSERT INTO localities (name, id_province, prefix) values ("Aldea brasilera", 7, "343");
INSERT INTO localities (name, id_province, prefix) values ("Aldea san antonio", 7, "3446");
INSERT INTO localities (name, id_province, prefix) values ("Altamirano (prov. Entre rios)", 7, "3445");
INSERT INTO localities (name, id_province, prefix) values ("Aranguren", 7, "3436");
INSERT INTO localities (name, id_province, prefix) values ("Calabacillas", 7, "345");
INSERT INTO localities (name, id_province, prefix) values ("Caseros", 7, "3442");
INSERT INTO localities (name, id_province, prefix) values ("Centenario (prov. Entre rios)", 7, "3437");
INSERT INTO localities (name, id_province, prefix) values ("Chajari", 7, "3456");
INSERT INTO localities (name, id_province, prefix) values ("Clara", 7, "3455");
INSERT INTO localities (name, id_province, prefix) values ("Conscripto bernardi", 7, "3454");
INSERT INTO localities (name, id_province, prefix) values ("Cuchilla", 7, "3444");
INSERT INTO localities (name, id_province, prefix) values ("Los conquistadores", 7, "3458");
INSERT INTO localities (name, id_province, prefix) values ("Clorinda", 8, "3718");
INSERT INTO localities (name, id_province, prefix) values ("Colonia pastoril", 8, "370");
INSERT INTO localities (name, id_province, prefix) values ("Comandante fontana", 8, "3716");
INSERT INTO localities (name, id_province, prefix) values ("Abra pampa", 9, "3887");
INSERT INTO localities (name, id_province, prefix) values ("Agua caliente (dto. Cochinoca)", 9, "3888");
INSERT INTO localities (name, id_province, prefix) values ("Agua caliente (dto. El carmen)", 9, "388");
INSERT INTO localities (name, id_province, prefix) values ("Caimancito", 9, "3886");
INSERT INTO localities (name, id_province, prefix) values ("Casira", 9, "3885");
INSERT INTO localities (name, id_province, prefix) values ("Adolfo van praet", 10, "2331");
INSERT INTO localities (name, id_province, prefix) values ("Agustoni", 10, "2302");
INSERT INTO localities (name, id_province, prefix) values ("Algarrobo del aguila", 10, "2338");
INSERT INTO localities (name, id_province, prefix) values ("Alpachiri (prov. La pampa)", 10, "2953");
INSERT INTO localities (name, id_province, prefix) values ("Anguil", 10, "2954");
INSERT INTO localities (name, id_province, prefix) values ("Arata", 10, "2335");
INSERT INTO localities (name, id_province, prefix) values ("Chacharramendi", 10, "2952");
INSERT INTO localities (name, id_province, prefix) values ("Colonia baron", 10, "2333");
INSERT INTO localities (name, id_province, prefix) values ("Conhello", 10, "2334");
INSERT INTO localities (name, id_province, prefix) values ("Gobernador duval", 10, "298");
INSERT INTO localities (name, id_province, prefix) values ("Aimogasta", 11, "3827");
INSERT INTO localities (name, id_province, prefix) values ("Alto jague", 11, "3825");
INSERT INTO localities (name, id_province, prefix) values ("Amana", 11, "380");
INSERT INTO localities (name, id_province, prefix) values ("Chamical", 11, "3826");
INSERT INTO localities (name, id_province, prefix) values ("Chepes", 11, "3821");
INSERT INTO localities (name, id_province, prefix) values ("25 de mayo (prov. Mendoza)", 12, "260");
INSERT INTO localities (name, id_province, prefix) values ("Agrelo", 12, "261");
INSERT INTO localities (name, id_province, prefix) values ("Arroyito (prov. Mendoza)", 12, "2626");
INSERT INTO localities (name, id_province, prefix) values ("Bowen", 12, "2625");
INSERT INTO localities (name, id_province, prefix) values ("Cacheuta", 12, "2624");
INSERT INTO localities (name, id_province, prefix) values ("Campamentos", 12, "263");
INSERT INTO localities (name, id_province, prefix) values ("Colonia las rosas", 12, "2622");
INSERT INTO localities (name, id_province, prefix) values ("2 de mayo", 13, "3755");
INSERT INTO localities (name, id_province, prefix) values ("9 de julio (prov. Misiones)", 13, "3751");
INSERT INTO localities (name, id_province, prefix) values ("Almafuerte (prov. Misiones)", 13, "3754");
INSERT INTO localities (name, id_province, prefix) values ("Andresito", 13, "3757");
INSERT INTO localities (name, id_province, prefix) values ("Apostoles", 13, "3758");
INSERT INTO localities (name, id_province, prefix) values ("Bella vista", 13, "376");
INSERT INTO localities (name, id_province, prefix) values ("Bernardo de irigoyen", 13, "3741");
INSERT INTO localities (name, id_province, prefix) values ("Capiovi", 13, "3743");
INSERT INTO localities (name, id_province, prefix) values ("Aguada chacayco", 14, "2948");
INSERT INTO localities (name, id_province, prefix) values ("Alumine", 14, "2942");
INSERT INTO localities (name, id_province, prefix) values ("Anelo", 14, "299");
INSERT INTO localities (name, id_province, prefix) values ("Junin de los andes", 14, "2972");
INSERT INTO localities (name, id_province, prefix) values ("Arroyo de la ventana", 15, "2934");
INSERT INTO localities (name, id_province, prefix) values ("Bahia san blas", 15, "2920");
INSERT INTO localities (name, id_province, prefix) values ("Chimpay", 15, "2946");
INSERT INTO localities (name, id_province, prefix) values ("Colan conhue (prov. Rio negro)", 15, "2940");
INSERT INTO localities (name, id_province, prefix) values ("General conesa (prov. Rio negro)", 15, "2931");
INSERT INTO localities (name, id_province, prefix) values ("Aguaray", 16, "3873");
INSERT INTO localities (name, id_province, prefix) values ("Aguas blancas", 16, "3878");
INSERT INTO localities (name, id_province, prefix) values ("Angastaco", 16, "3868");
INSERT INTO localities (name, id_province, prefix) values ("Antilla", 16, "3876");
INSERT INTO localities (name, id_province, prefix) values ("Atocha", 16, "387");
INSERT INTO localities (name, id_province, prefix) values ("9 de julio (prov. San juan)", 17, "264");
INSERT INTO localities (name, id_province, prefix) values ("Astica", 17, "2646");
INSERT INTO localities (name, id_province, prefix) values ("Barreal", 17, "2648");
INSERT INTO localities (name, id_province, prefix) values ("Colanguil", 17, "2647");
INSERT INTO localities (name, id_province, prefix) values ("Alto pencoso", 18, "266");
INSERT INTO localities (name, id_province, prefix) values ("Anchorena", 18, "2658");
INSERT INTO localities (name, id_province, prefix) values ("Candelaria (prov. San luis)", 18, "2651");
INSERT INTO localities (name, id_province, prefix) values ("Carpinteria (prov. San luis)", 18, "2656");
INSERT INTO localities (name, id_province, prefix) values ("Fraga", 18, "2657");
INSERT INTO localities (name, id_province, prefix) values ("Juan llerena", 18, "2655");
INSERT INTO localities (name, id_province, prefix) values ("28 de noviembre", 19, "2902");
INSERT INTO localities (name, id_province, prefix) values ("Bajo caracoles", 19, "2963");
INSERT INTO localities (name, id_province, prefix) values ("Bella vista (prov. Santa cruz)", 19, "2966");
INSERT INTO localities (name, id_province, prefix) values ("Comandante luis piedra buena", 19, "2962");
INSERT INTO localities (name, id_province, prefix) values ("Acebal", 20, "3469");
INSERT INTO localities (name, id_province, prefix) values ("Aerodromo sauce viejo", 20, "342");
INSERT INTO localities (name, id_province, prefix) values ("Aguara grande", 20, "3408");
INSERT INTO localities (name, id_province, prefix) values ("Albarellos", 20, "3402");
INSERT INTO localities (name, id_province, prefix) values ("Alcorta", 20, "3465");
INSERT INTO localities (name, id_province, prefix) values ("Aldao", 20, "3476");
INSERT INTO localities (name, id_province, prefix) values ("Alejandra", 20, "3405");
INSERT INTO localities (name, id_province, prefix) values ("Ambrosetti", 20, "3491");
INSERT INTO localities (name, id_province, prefix) values ("Angelica", 20, "3492");
INSERT INTO localities (name, id_province, prefix) values ("Arequito", 20, "3464");
INSERT INTO localities (name, id_province, prefix) values ("Armstrong", 20, "3471");
INSERT INTO localities (name, id_province, prefix) values ("Arocena", 20, "3466");
INSERT INTO localities (name, id_province, prefix) values ("Arroyo ceibal", 20, "3482");
INSERT INTO localities (name, id_province, prefix) values ("Ataliva", 20, "3493");
INSERT INTO localities (name, id_province, prefix) values ("Calchaqui", 20, "3483");
INSERT INTO localities (name, id_province, prefix) values ("Campo andino", 20, "3497");
INSERT INTO localities (name, id_province, prefix) values ("Campo castro", 20, "3401");
INSERT INTO localities (name, id_province, prefix) values ("Campo piaggio", 20, "3404");
INSERT INTO localities (name, id_province, prefix) values ("Canada rica", 20, "3460");
INSERT INTO localities (name, id_province, prefix) values ("Capitan bermudez", 20, "341");
INSERT INTO localities (name, id_province, prefix) values ("Carmen", 20, "3462");
INSERT INTO localities (name, id_province, prefix) values ("Castelar", 20, "3406");
INSERT INTO localities (name, id_province, prefix) values ("Cavour", 20, "3496");
INSERT INTO localities (name, id_province, prefix) values ("Colonia bossi", 20, "3409");
INSERT INTO localities (name, id_province, prefix) values ("Elisa", 20, "3498");
INSERT INTO localities (name, id_province, prefix) values ("Empalme villa constitucion", 20, "3400");
INSERT INTO localities (name, id_province, prefix) values ("Ancajan", 21, "3854");
INSERT INTO localities (name, id_province, prefix) values ("Antaje", 21, "385");
INSERT INTO localities (name, id_province, prefix) values ("Anatuya", 21, "3844");
INSERT INTO localities (name, id_province, prefix) values ("Arenales", 21, "3861");
INSERT INTO localities (name, id_province, prefix) values ("Bandera", 21, "3857");
INSERT INTO localities (name, id_province, prefix) values ("Bandera bajada", 21, "3855");
INSERT INTO localities (name, id_province, prefix) values ("Brea pozo", 21, "3845");
INSERT INTO localities (name, id_province, prefix) values ("Campo gallo", 21, "3846");
INSERT INTO localities (name, id_province, prefix) values ("Colonia tinco", 21, "3858");
INSERT INTO localities (name, id_province, prefix) values ("El 49 (km. 49)", 21, "3856");
INSERT INTO localities (name, id_province, prefix) values ("Monte quemado", 21, "3841");
INSERT INTO localities (name, id_province, prefix) values ("Quimili", 21, "3843");
INSERT INTO localities (name, id_province, prefix) values ("Las cotorras", 22, "2901");
INSERT INTO localities (name, id_province, prefix) values ("Rio grande", 22, "2964");
INSERT INTO localities (name, id_province, prefix) values ("Acheral", 23, "3863");