INSERT INTO provinces (id_province ,name) values (1,"Buenos aires");
INSERT INTO provinces (id_province ,name) values (2,"Catamarca");
INSERT INTO provinces (id_province ,name) values (3,"Chaco");
INSERT INTO provinces (id_province ,name) values (4,"Chubut");
INSERT INTO provinces (id_province ,name) values (5,"Cordoba");
INSERT INTO provinces (id_province ,name) values (6,"Corrientes");
INSERT INTO provinces (id_province ,name) values (7,"Entre rios");
INSERT INTO provinces (id_province ,name) values (8,"Formosa");
INSERT INTO provinces (id_province ,name) values (9,"Jujuy");
INSERT INTO provinces (id_province ,name) values (10,"La pampa");
INSERT INTO provinces (id_province ,name) values (11,"La rioja");
INSERT INTO provinces (id_province ,name) values (12,"Mendoza");
INSERT INTO provinces (id_province ,name) values (13,"Misiones");
INSERT INTO provinces (id_province ,name) values (14,"Neuquen");
INSERT INTO provinces (id_province ,name) values (15,"Rio negro");
INSERT INTO provinces (id_province ,name) values (16,"Salta");
INSERT INTO provinces (id_province ,name) values (17,"San juan");
INSERT INTO provinces (id_province ,name) values (18,"San luis");
INSERT INTO provinces (id_province ,name) values (19,"Santa cruz");
INSERT INTO provinces (id_province ,name) values (20,"Santa fe");
INSERT INTO provinces (id_province ,name) values (21,"Santiago del estero");
INSERT INTO provinces (id_province ,name) values (22,"Tierra del fuego");
INSERT INTO provinces (id_province ,name) values (23,"Tucuman");