#spring:
#  h2:
#    console:
#     enabled: true
#     path: /h2-console
#
#  jpa:
#    show-sql: true
#jdbc:h2:mem:testdb
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/utnphones #jdbc:mysql://db4free.net:3306/latorrerondinara
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update