#spring:
#  h2:
#    console:
#     enabled: true
#     path: /h2-console
#
#  jpa:
#    show-sql: true
#jdbc:h2:mem:testdb
spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/latorrerondinara
    username: utnphones
    password: tusi2020
  jpa:
    hibernate:
      ddl-auto: create-drop