#spring:
#  h2:
#    console:
#     enabled: true
#     path: /h2-console
#
#  jpa:
#    show-sql: true
#jdbc:h2:mem:testdb
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/utnphones
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
#spring:
#  datasource:
#    url: jdbc:mysql://db4free.net:3306/latorrerondinara #jdbc:mysql://localhost:3306/utnphones #
#    username: utnphones
#    password: tusi2020
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
